project:
  type: book
  output-dir: docs

book:
  title: "CORN3005-ESM"
  author: "Michael Hunt"
  date: "9/28/2025"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) Michael Hunt
  chapters:
    - index.qmd
    - simple_climate_model.qmd
    - PVA_grizzly.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    df_print: paged
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  message: false
  warning: false



